modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="citycraft"
version="1.0.09"
displayName="City Craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Yao_Child"
description='''
Help you to build cities easily!
'''

[[dependencies.citycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




